### ISSUE TITLE
Possible incorrect answer for 'Can multiple Pod Security Admission (PSA) policies be applied to a single namespace?'

### ISSUE THREAD

**Issue by amimas** [thiago4go/kubernetes-security-kcsa-mock#4]
Hello,

I feel the answer configured for the question 'Can multiple Pod Security Admission (PSA) policies be applied to a single namespace?' is incorrect. Right now, the correct answer configured to be 'No, only one policy level per namespace'.

https://github.com/thiago4go/kubernetes-security-kcsa-mock/blob/f5c531e37eae5b087b906cd708e345a7b6fbd43d/src/questions.js#L30-L43

But, it is possible to apply multiple policies, isn't it? For example: set `enforce` for a loose policy and use `warn` or `audit` to get insight about more restricted policy and how it could affect resources.

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: my-baseline-namespace
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: v1.32

    # We are setting these to our _desired_ `enforce` level.
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.32
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.32
```

Ref: https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-namespace-labels/

The docs for [Pod Security Admission labels for namespaces](https://kubernetes.io/docs/concepts/security/pod-security-admission/#pod-security-admission-labels-for-namespaces) also mentions following in addition to above example:

> A namespace can configure any or all modes, or even set a different level for different modes.

Am I mis-interpreting the question?
